package secundario;

import java.util.LinkedList;
import javax.swing.ImageIcon;

import principal.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
@SuppressWarnings("serial")
public class InHistMed extends javax.swing.JFrame {
    private PersonalAdm usuario;
    @SuppressWarnings({ "unchecked", "rawtypes" })
	LinkedList<String> s = new LinkedList();
    String Enfermedades = "";
    String Sgroup = "";
    String Incap = "";
    boolean Correcto[] = new boolean [5];
    boolean pasa = true;
    
    public InHistMed(){}
    
    public InHistMed(PersonalAdm u) {
        this.usuario = u;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SiAsma = new javax.swing.JCheckBox();
        NoAsma = new javax.swing.JCheckBox();
        NoDiabetes = new javax.swing.JCheckBox();
        SiDiabetes = new javax.swing.JCheckBox();
        NoHiperten = new javax.swing.JCheckBox();
        SiHiperten = new javax.swing.JCheckBox();
        SiTuberculosis = new javax.swing.JCheckBox();
        NoTuberculosis = new javax.swing.JCheckBox();
        SiEnfCar = new javax.swing.JCheckBox();
        NoEnfCar = new javax.swing.JCheckBox();
        OtraEnfermedad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        IncMental = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        IncFisica = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        GrupoS = new javax.swing.JComboBox<>();
        Factor = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        Alergic = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TratyOt = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Historial");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 170, 58);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Médico");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 50, 148, 58);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Asma Bronquial");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 130, 93, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Diabetes");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 170, 52, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Hipertensión");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 210, 75, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tuberculosis");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 250, 75, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Enfermedades Cardíacas");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 290, 149, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Otra");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 330, 27, 17);

        SiAsma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SiAsma.setText("Si");
        SiAsma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiAsmaActionPerformed(evt);
            }
        });
        getContentPane().add(SiAsma);
        SiAsma.setBounds(230, 130, 35, 25);

        NoAsma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NoAsma.setText("No");
        NoAsma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoAsmaActionPerformed(evt);
            }
        });
        getContentPane().add(NoAsma);
        NoAsma.setBounds(270, 130, 43, 25);

        NoDiabetes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NoDiabetes.setText("No");
        NoDiabetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoDiabetesActionPerformed(evt);
            }
        });
        getContentPane().add(NoDiabetes);
        NoDiabetes.setBounds(270, 170, 43, 25);

        SiDiabetes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SiDiabetes.setText("Si");
        SiDiabetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiDiabetesActionPerformed(evt);
            }
        });
        getContentPane().add(SiDiabetes);
        SiDiabetes.setBounds(230, 170, 35, 25);

        NoHiperten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NoHiperten.setText("No");
        NoHiperten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoHipertenActionPerformed(evt);
            }
        });
        getContentPane().add(NoHiperten);
        NoHiperten.setBounds(270, 210, 43, 25);

        SiHiperten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SiHiperten.setText("Si");
        SiHiperten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiHipertenActionPerformed(evt);
            }
        });
        getContentPane().add(SiHiperten);
        SiHiperten.setBounds(230, 210, 35, 25);

        SiTuberculosis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SiTuberculosis.setText("Si");
        SiTuberculosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiTuberculosisActionPerformed(evt);
            }
        });
        getContentPane().add(SiTuberculosis);
        SiTuberculosis.setBounds(230, 250, 35, 25);

        NoTuberculosis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NoTuberculosis.setText("No");
        NoTuberculosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoTuberculosisActionPerformed(evt);
            }
        });
        getContentPane().add(NoTuberculosis);
        NoTuberculosis.setBounds(270, 250, 43, 25);

        SiEnfCar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SiEnfCar.setText("Si");
        SiEnfCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiEnfCarActionPerformed(evt);
            }
        });
        getContentPane().add(SiEnfCar);
        SiEnfCar.setBounds(230, 290, 35, 25);

        NoEnfCar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NoEnfCar.setText("No");
        NoEnfCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoEnfCarActionPerformed(evt);
            }
        });
        getContentPane().add(NoEnfCar);
        NoEnfCar.setBounds(270, 290, 43, 25);

        OtraEnfermedad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OtraEnfermedad.setText("Ninguna");
        getContentPane().add(OtraEnfermedad);
        OtraEnfermedad.setBounds(230, 330, 241, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Incapacidades Mentales");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 380, 149, 17);

        IncMental.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IncMental.setText("Ninguna");
        getContentPane().add(IncMental);
        IncMental.setBounds(230, 370, 241, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Incapacidades Físicas");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(90, 420, 127, 17);

        IncFisica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IncFisica.setText("Ninguna");
        getContentPane().add(IncFisica);
        IncFisica.setBounds(230, 420, 241, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Grupo Sanguíneo");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(110, 460, 106, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Factor");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(180, 500, 39, 17);

        GrupoS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GrupoS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "0" }));
        getContentPane().add(GrupoS);
        GrupoS.setBounds(230, 460, 241, 23);

        Factor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Factor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RH+", "RH-" }));
        getContentPane().add(Factor);
        Factor.setBounds(230, 500, 241, 23);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Alérgico a alguna droga");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(70, 540, 149, 17);

        Alergic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Alergic.setText("Ninguna");
        getContentPane().add(Alergic);
        Alergic.setBounds(230, 540, 241, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 620, 127, 33);

        TratyOt.setColumns(20);
        TratyOt.setRows(5);
        TratyOt.setMaximumSize(new java.awt.Dimension(164, 94));
        jScrollPane2.setViewportView(TratyOt);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(510, 140, 410, 420);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tratamientos en proceso u otra información relevante:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(510, 110, 360, 17);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Añadir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(393, 570, 80, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-6, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SiAsmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiAsmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiAsmaActionPerformed

    private void NoAsmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoAsmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoAsmaActionPerformed

    private void NoDiabetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoDiabetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoDiabetesActionPerformed

    private void SiDiabetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiDiabetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiDiabetesActionPerformed

    private void NoHipertenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoHipertenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoHipertenActionPerformed

    private void SiHipertenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiHipertenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiHipertenActionPerformed

    private void SiTuberculosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiTuberculosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiTuberculosisActionPerformed

    private void NoTuberculosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoTuberculosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoTuberculosisActionPerformed

    private void SiEnfCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiEnfCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiEnfCarActionPerformed

    private void NoEnfCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoEnfCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoEnfCarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean alguna = false;
        CamposVacios dv = new CamposVacios(usuario);
        Correcto [0] = false;
        Correcto [1] = false;
        Correcto [2] = false;
        Correcto [3] = false;
        Correcto [4] = false;
        if((SiAsma.isSelected())&&!(NoAsma.isSelected()))
        {
            Enfermedades = Enfermedades + "\n  Asma";
            Correcto [0] = true;
            alguna = true;
        }
        if(!(SiAsma.isSelected())&&(NoAsma.isSelected()))
        {
            Correcto [0] = true;
        }
        if((!SiAsma.isSelected())&&!(NoAsma.isSelected()))
        {
            dv.setVisible(true);
        }
        if((SiAsma.isSelected())&&(NoAsma.isSelected()))
        {
            dv.setVisible(true);
        }
        if((SiDiabetes.isSelected())&&!(NoDiabetes.isSelected()))
        {
            Enfermedades = Enfermedades + "\n  Diabetes";
            Correcto [1] = true;
            alguna = true;
        }
        if(!(SiDiabetes.isSelected())&&(NoDiabetes.isSelected()))
        {
            Correcto [1] = true;
        }
        if((!SiDiabetes.isSelected())&&!(NoDiabetes.isSelected()))
        {
            dv.setVisible(true);
        }
        if((SiDiabetes.isSelected())&&(NoDiabetes.isSelected()))
        {
            dv.setVisible(true);
        }
        if((SiHiperten.isSelected())&&!(NoHiperten.isSelected()))
        {
            Enfermedades = Enfermedades + "\n  Hipertenso/a";
            Correcto [2] = true;
            alguna = true;
        }
        if(!(SiHiperten.isSelected())&&(NoHiperten.isSelected()))
        {
            Correcto [2] = true;
        }
        if((!SiHiperten.isSelected())&&!(NoHiperten.isSelected()))
        {
            dv.setVisible(true);
        }
        if((SiHiperten.isSelected())&&(NoHiperten.isSelected()))
        {
            dv.setVisible(true);
        }
        if((SiTuberculosis.isSelected())&&!(NoTuberculosis.isSelected()))
        {
            Enfermedades = Enfermedades + "\n  Tuberculosis";
            Correcto [3] = true;
            alguna = true;
        }
        if(!(SiTuberculosis.isSelected())&&(NoTuberculosis.isSelected()))
        {
            Correcto [3] = true;
        }
        if((!SiTuberculosis.isSelected())&&!(NoTuberculosis.isSelected()))
        {
            dv.setVisible(true);
        }
        if((SiTuberculosis.isSelected())&&(NoTuberculosis.isSelected()))
        {
            dv.setVisible(true);
        }
        if((SiEnfCar.isSelected())&&!(NoEnfCar.isSelected()))
        {
            Enfermedades = Enfermedades + "\n  Enfermedades Cardiacas";
            Correcto [4] = true;
            alguna = true;
        }
        if(!(SiEnfCar.isSelected())&&(NoEnfCar.isSelected()))
        {
            Correcto [4] = true;
        }
        if((!SiEnfCar.isSelected())&&!(NoEnfCar.isSelected()))
        {
            dv.setVisible(true);
        }
        if((SiEnfCar.isSelected())&&(NoEnfCar.isSelected()))
        {
            dv.setVisible(true);
        }
        if(!OtraEnfermedad.getText().equals("Ninguna"))
        {
            Enfermedades = Enfermedades +"\n  "+ OtraEnfermedad.getText();
            alguna = true;
        }
        if(!alguna)
        {
            Enfermedades = "Ninguna";
        }
        //if(!IncFisica.getText().equals("Ninguna"))
        //{
            Incap = Incap +"\n  Fisicas: "+ IncFisica.getText() + "\n";
        //}
        //if(!IncMental.getText().equals("Ninguna"))
        //{
            Incap = Incap +"  Mentales: "+ IncMental.getText();
        //}
        Sgroup=(String)GrupoS.getSelectedItem()+" "+(String)Factor.getSelectedItem();
        for(int i = 0;i<Correcto.length;i++)
        {
            if(Correcto[i]==false)
            {
                pasa = false;
            }
            else
            {
                pasa = true;
            }
        }
        if(pasa)
        {
            for(int i = 0;i<usuario.getAllPacientes().size();i++)
            {
                if(usuario.getAllPacientes().get(i).esSelect)
                {
                    usuario.getAllPacientes().get(i).setHistorial(new HistorialMedico(TratyOt.getText(),Enfermedades,Sgroup,Incap,s));
                }
            }
            HistCorrecto h = new HistCorrecto(usuario);
            h.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(Alergic.getText().equals(""))
        {
            CamposVacios dv = new CamposVacios();
            dv.setVisible(true);
        }
        else
        {
            usuario.getPacienteSel().getAlergias().add(new Medicamento(Alergic.getText()));
            s.add("\n  "+Alergic.getText());
            Alergic.setText(null);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InHistMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InHistMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InHistMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InHistMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InHistMed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alergic;
    private javax.swing.JComboBox<String> Factor;
    private javax.swing.JComboBox<String> GrupoS;
    private javax.swing.JTextField IncFisica;
    private javax.swing.JTextField IncMental;
    private javax.swing.JCheckBox NoAsma;
    private javax.swing.JCheckBox NoDiabetes;
    private javax.swing.JCheckBox NoEnfCar;
    private javax.swing.JCheckBox NoHiperten;
    private javax.swing.JCheckBox NoTuberculosis;
    private javax.swing.JTextField OtraEnfermedad;
    private javax.swing.JCheckBox SiAsma;
    private javax.swing.JCheckBox SiDiabetes;
    private javax.swing.JCheckBox SiEnfCar;
    private javax.swing.JCheckBox SiHiperten;
    private javax.swing.JCheckBox SiTuberculosis;
    private javax.swing.JTextArea TratyOt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
