/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package secundario;

import principal.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
