package pruebaGradle;

import java.util.ArrayList;
import javax.swing.ImageIcon;

@SuppressWarnings({ "unused", "serial" })
public class Aut extends javax.swing.JFrame {

    private PersonalAdm usuario;
    public Aut(){}
    
    public Aut(PersonalAdm p) {
        this.usuario = p;
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("../Imagenes/Icon.png")).getImage());
        this.setSize(1000, 800);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        TipoUser = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IDtext = new javax.swing.JTextField();
        PassText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        NomDoc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IDDoc = new javax.swing.JTextField();
        PassDoc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        PassGes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGCP");
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        TipoUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Doctor", "Personal Administrativo" }));
        TipoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoUserActionPerformed(evt);
            }
        });
        jPanel3.add(TipoUser);
        TipoUser.setBounds(420, 260, 160, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ingresar como:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(310, 250, 100, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(390, 300, 14, 17);

        IDtext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(IDtext);
        IDtext.setBounds(420, 300, 160, 23);

        PassText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PassText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassTextActionPerformed(evt);
            }
        });
        jPanel3.add(PassText);
        PassText.setBounds(420, 340, 160, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(340, 330, 70, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Ingresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(463, 380, 110, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("../Imagenes/Fondo.png"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 990, 770);
        
        jTabbedPane3.addTab("Personal Administrativo", jPanel3);

        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setText("Ingresar Nuevo Doctor");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 20, 490, 140);

        NomDoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(NomDoc);
        NomDoc.setBounds(430, 280, 160, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nombre");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(370, 280, 49, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("ID");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(400, 310, 14, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Contraseña del nuevo usuario");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(230, 340, 190, 17);

        IDDoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(IDDoc);
        IDDoc.setBounds(430, 310, 160, 23);

        PassDoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PassDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassDocActionPerformed(evt);
            }
        });
        jPanel4.add(PassDoc);
        PassDoc.setBounds(430, 340, 160, 23);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(480, 410, 108, 25);

        PassGes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(PassGes);
        PassGes.setBounds(430, 370, 160, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Contraseña del Gestor");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(280, 370, 135, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("../Imagenes/Fondo.png"))); // NOI18N
        jPanel4.add(jLabel9);
        jLabel9.setBounds(0, 0, 990, 770);

        jTabbedPane3.addTab("Gestión de Usuarios", jPanel4);

        getContentPane().add(jTabbedPane3);
        jTabbedPane3.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PassTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassTextActionPerformed

    @SuppressWarnings("unlikely-arg-type")
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String a="";
        String pass;
        boolean correcto = false; 
           if(TipoUser.getSelectedIndex()==0)
           {
               IDtext.setText(null);
               PassText.setText(null);
               SelUsuario sel = new SelUsuario();
               sel.setVisible(true);
           }
           else
           {
               if(!(!(PassText.getText().equals(""))&&!(IDtext.equals(""))))
           {
               CamposVacios cv = new CamposVacios(usuario);
               cv.setVisible(true);
               this.PassText.setText(null);
               this.IDtext.setText(null);
           }
               else
           {
               try{
               a=IDtext.getText();
               }catch(Exception e){};
               if(TipoUser.getSelectedIndex()==1)
                {   
                    for(int i = 0;i<usuario.getMisObservers().size();i++)
                    {
                        pass=usuario.getMisObservers().get(i).getPassword();
                        if((pass.equals(PassText.getText()))&&(usuario.getMisObservers().get(i).getID().equals(a)))
                        {   
                            correcto = true;
                            usuario.SelDoctor(usuario.getMisObservers().get(i).getID());
                            //usuario.getMisObservers().get(i).setSelect();
                        }
                    }
                    if(correcto)
                    {
                        PrincipalDoctor open = new PrincipalDoctor(usuario);
                        open.setVisible(true);
                        this.setVisible(false);
                    }
                    else
                    {
                        ErrorAuten error = new ErrorAuten();
                        error.setVisible(true);
                        IDtext.setText(null);
                        PassText.setText(null);
                    }
                }
                if(TipoUser.getSelectedIndex()==2)
                {
                    pass=usuario.getPassword();
                    if((pass.equals(PassText.getText()))&&(usuario.getID().equals(a)))
                    {
                        correcto = true;
                        usuario.setSelect();
                    }
                    if(correcto)
                    {
                        PrincipalAdmin abrir = new PrincipalAdmin(usuario);
                        abrir.setVisible(true);
                        this.setVisible(false);
                    }
                    else
                    {
                        ErrorAuten error = new ErrorAuten();
                        error.setVisible(true);
                        IDtext.setText(null);
                        PassText.setText(null);
                    }
                }
           }
           }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PassDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassDocActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String aux[] = new String [4];
        aux[0] = NomDoc.getText();
        aux[1] = IDDoc.getText();
        aux[2] = PassDoc.getText();
        aux[3] = PassGes.getText();
        if(aux[0].equals("")||aux[1].equals("")||aux[2].equals("")||aux[3].equals(""))
        {
            CamposVacios c = new CamposVacios(usuario);
            c.setVisible(true);
            NomDoc.setText(null);
            IDDoc.setText(null);
            PassDoc.setText(null);
            PassGes.setText(null);
        }
        else
        {
            if(aux[3].equals("4321"))
            {
                new Doctor(aux[0],aux[1],aux[2],usuario);
                NomDoc.setText(null);
                IDDoc.setText(null);
                PassDoc.setText(null);
                PassGes.setText(null);
                this.setVisible(false);
                DCorrecto d = new DCorrecto(usuario);
                d.setVisible(true);
            }
            else
            {
                ErrorAuten v = new ErrorAuten();
                v.setVisible(true);
                NomDoc.setText(null);
                IDDoc.setText(null);
                PassDoc.setText(null);
                PassGes.setText(null);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TipoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDDoc;
    private javax.swing.JTextField IDtext;
    private javax.swing.JTextField NomDoc;
    private javax.swing.JTextField PassDoc;
    private javax.swing.JTextField PassGes;
    private javax.swing.JTextField PassText;
    private javax.swing.JComboBox<String> TipoUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables

    private void setIconImage(ImageIcon imageIcon) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}