package pruebaGradle;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
/**
 *
 * @author Lucas
 */
@SuppressWarnings("serial")
public class Cobrar extends javax.swing.JFrame {

    private PersonalAdm usuario;
    Efectivo e = new Efectivo();
    Mutual m = new Mutual();
    Tarjeta t = new Tarjeta();
    
    public Cobrar(){}
     
    @SuppressWarnings({ "rawtypes", "unchecked" })
	public Cobrar(PersonalAdm u) {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Icon.png")).getImage());
        this.setLocationRelativeTo(null);
        this.usuario = u;
        DefaultListModel cb2= new DefaultListModel();
        int b = 0;
        b=usuario.getAllPacientes().size();
        String aux="";
        String aux2="";
        Paciente.setModel(cb2);
        for(int i = 0; i<b;i++)
        {   
            try
            {
                aux = usuario.getAllPacientes().get(i).getNombre()+" "+usuario.getAllPacientes().get(i).getApellido()+" "+usuario.getAllPacientes().get(i).getDni();
                if(usuario.getAllPacientes().get(i).getDeuda())
                {
                    aux2=" Adeuda"; 
                }
                else
                {
                    aux2=" No Adeuda";   
                }
                aux += aux2;
            }
            catch (Exception e){}
           cb2.addElement(aux);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Paciente = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cobrar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        SelMetP = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(null);

        Paciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Paciente.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                PacienteValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(Paciente);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(65, 126, 495, 450);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Cobro de Consultas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 11, 410, 97);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Método de Pago");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(587, 129, 100, 17);

        Cobrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cobrar.setText("Cobrar");
        Cobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CobrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cobrar);
        Cobrar.setBounds(757, 167, 168, 67);

        Volver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver);
        Volver.setBounds(757, 252, 168, 67);

        SelMetP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SelMetP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Pago en Efectivo", "Pago con Tarjeta", "Pago con Mutual" }));
        SelMetP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelMetPActionPerformed(evt);
            }
        });
        getContentPane().add(SelMetP);
        SelMetP.setBounds(705, 129, 220, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
	private void CobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CobrarActionPerformed
        if(SelMetP.getSelectedIndex()!=0)
        {
            if(Paciente.getSelectedIndex()!=-1)
            {
                if(usuario.getPacienteSel().getDeuda())
                {
                    String s = usuario.getPacienteSel().Pagar();
                    Pagado p = new Pagado(usuario,s);
                    p.setVisible(true);
                    usuario.getPacienteSel().setDeuda(false);
                    @SuppressWarnings("rawtypes")
					DefaultListModel cb2= new DefaultListModel();
                    int b = 0;
                    b=usuario.getAllPacientes().size();
                    String aux="";
                    String aux2="";
                    Paciente.setModel(cb2);
                    for(int i = 0; i<b;i++)
                    {   
                        try
                        {
                            aux = usuario.getAllPacientes().get(i).getNombre()+" "+usuario.getAllPacientes().get(i).getApellido()+" "+usuario.getAllPacientes().get(i).getDni();
                            if(usuario.getAllPacientes().get(i).getDeuda())
                            {
                                aux2=" Adeuda"; 
                            }
                            else
                            {
                                aux2=" No Adeuda";   
                            }
                            aux += aux2;
                        }
                        catch (Exception e){}
                        cb2.addElement(aux);
                    }
                }
                else
                {
                    NoAdeuda n = new NoAdeuda(usuario);
                    n.setVisible(true);
                }     
            }
        }
        else
        {
            CamposVacios c = new CamposVacios (usuario);
            c.setVisible(true);
        }
    }//GEN-LAST:event_CobrarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        PrincipalAdmin p = new PrincipalAdmin(usuario);
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    private void PacienteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_PacienteValueChanged
        int a = Paciente.getSelectedIndex();
        usuario.SelPaciente(a);
    }//GEN-LAST:event_PacienteValueChanged

    private void SelMetPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelMetPActionPerformed
        int a = SelMetP.getSelectedIndex();
        if(a!=0)
        {
            if(a==1)
            {
                usuario.getPacienteSel().setfdp(e);
            }
            if(a==2)
            {
                usuario.getPacienteSel().setfdp(t);
            }
            if(a==3)
            {
                usuario.getPacienteSel().setfdp(m);
            }
        }
    }//GEN-LAST:event_SelMetPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cobrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cobrar;
    private javax.swing.JList<String> Paciente;
    private javax.swing.JComboBox<String> SelMetP;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}

