package pruebaGradle;


import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
@SuppressWarnings("serial")
public class Recetar extends javax.swing.JFrame {

    private PersonalAdm usuario;
    
    public Recetar(){}
    
    public Recetar(PersonalAdm u) {
        this.usuario = u;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Icon.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Medicam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(385, 180));
        setResizable(false);
        setSize(new java.awt.Dimension(385, 180));
        getContentPane().setLayout(null);

        Mensaje.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Mensaje);
        Mensaje.setBounds(22, 50, 0, 0);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 100, 95, 38);

        Medicam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Medicam);
        Medicam.setBounds(20, 40, 340, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Recetar: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 210, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mensajes.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, 0, 390, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        @SuppressWarnings("unused")
		String est="";
        String s = Medicam.getText();
        boolean esAl = false;
        if(s.equals(""))
        {
            CamposVacios c = new CamposVacios(usuario);
            c.setVisible(true);
        }
        else
        {
            for(int i =0;i<usuario.getPacienteSel().getAlergias().size();i++)
            {
                if(usuario.getPacienteSel().getAlergias().get(i).getNombre().equals(s))
                {
                    esAlergic e = new esAlergic(usuario);
                    e.setVisible(true);
                    this.setVisible(false);
                    esAl=true;
                }
            }
            if(!esAl)
            {
                usuario.getDoctorSel().getPacienteSel().addMedicamento(new Medicamento(s));
            }
            this.setVisible(false);
            VerMisPacientes v = new VerMisPacientes(usuario);
            v.setVisible(true);
        }
                
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CamposVacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CamposVacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CamposVacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CamposVacios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CamposVacios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Medicam;
    private javax.swing.JLabel Mensaje;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
